---
apiVersion: skaffold/v2beta7
kind: Config

deploy:
  helm:
    releases:
    - name: gateway
      chartPath: ../../kubernetes/gateway
      valuesFiles:
      - ../../kubernetes/gateway/values.yaml
      version: 0.1.0
      # namespace: default
