---
server.port: 9001
server.error.include-message: always
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://0.0.0.0:5432/catalog-service
    username: postgres
    password: admin
logging:
  level:
    root: INFO
    com.fabijanbajo: DEBUG
    org.springframework.data.r2dbc: DEBUG

---
spring.profiles: docker
server.port: ${SERVER_PORT}
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PW}
logging:
  level:
    root: ${LOGGER_LEVEL}
management:
  health.probes.enabled: true