env:
  commonjs: true
  node: true
extends:
- google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
- '@typescript-eslint'
rules:
  require-jsdoc: 0
  new-cap: 0
  no-invalid-this: 0
  '@typescript-eslint/explicit-member-accessibility':
  - error
  '@typescript-eslint/no-unused-vars':
  - warn
