apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: identity-service
    context: .

deploy:
  helm:
    releases:
    - name: identity-service
      chartPath: ../../kubernetes/identity-service
      valuesFiles:
      - ../../kubernetes/identity-service/values.yaml
      artifactOverrides:
        image.repository: identity-service
      version: 0.1.0
      # namespace: default
