apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/fabijanbajo/webshop-order-service
    context: .

deploy:
  helm:
    releases:
    - name: order-service
      chartPath: kubernetes/order-service
      valuesFiles:
      - kubernetes/order-service/values.yaml
      artifactOverrides:
        image.repository: gcr.io/fabijanbajo/webshop-order-service
      version: 0.1.0
      namespace: default
