---
server.port: 9001
server.error.include-message: always
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://0.0.0.0:5432/product-service
    username: postgres
    password: admin
logging:
  level:
    root: INFO
    com.fabijanbajo: DEBUG
    org.springframework.data.r2dbc: DEBUG
  
---
spring.profiles: docker
server.port: 9001
spring:
  r2dbc:
    url: r2dbc:pool:postgres://postgresql-master:5432/product-service
    username: admin
    password: admin
logging:
  level:
    root: INFO
    com.fabijanbajo: DEBUG
    org.springframework.data.r2dbc: DEBUG
