---
version: "3.8"
services: 

  catalog-service:
    container_name: catalog-service
    build: .
    mem_limit: 350m
    ports:
    - 9001:9001
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - LOGGER_LEVEL=INFO
    - POSTGRES_HOST=postgresql-master
    - POSTGRES_PORT=5432 
    - POSTGRES_DB=catalog-service
    - POSTGRES_USER=postgres
    - POSTGRES_PW=admin
    depends_on:
    - postgresql-master

  postgresql-master:
    image: bitnami/postgresql:12
    container_name: postgresql-master
    ports:
    - 5432:5432
    volumes:
    - .data/postgresql_master:/bitnami/postgresql
    environment:
    - POSTGRESQL_USERNAME=admin
    - POSTGRESQL_PASSWORD=admin
    - POSTGRESQL_POSTGRES_PASSWORD=admin
    - POSTGRESQL_DATABASE=catalog-service
    # - POSTGRESQL_REPLICATION_MODE=master
    # - POSTGRESQL_REPLICATION_USER=repl
    # - POSTGRESQL_REPLICATION_PASSWORD=repl
  # postgresql-slave:
  #   image: bitnami/postgresql:12
  #   container_name: postgresql-slave
  #   ports:
  #   - 5432
  #   depends_on:
  #   - postgresql-master
  #   environment:
  #   - POSTGRESQL_REPLICATION_MODE=slave
  #   - POSTGRESQL_REPLICATION_USER=repl
  #   - POSTGRESQL_REPLICATION_PASSWORD=repl
  #   - POSTGRESQL_MASTER_HOST=postgresql-master
  #   - POSTGRESQL_PASSWORD=admin
  #   - POSTGRESQL_MASTER_PORT_NUMBER=5432

