---
version: "3.8"
services: 

  postgresql-master:
    image: bitnami/postgresql:12
    container_name: postgresql-master
    ports:
    - 5432:5432
    volumes:
    - .data/postgresql_master:/bitnami/postgresql
    environment:
    - POSTGRESQL_USERNAME=admin
    - POSTGRESQL_PASSWORD=admin
    - POSTGRESQL_POSTGRES_PASSWORD=admin
    - POSTGRESQL_DATABASE=catalog-service

  minio:
    image: minio/minio
    container_name: minio
    ports:
    - 9000:9000
    environment:
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    - MINIO_BROWSER=on
    command: server /data
