---
version: "3.8"
services: 
  catalog-service:
    build:
      context: .
    container_name: catalog-service
    ports:
    - 9001:9001
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_HOST=0.0.0.0
    - SERVER_PORT=9001
    - LOGGER_LEVEL=INFO
    - POSTGRES_HOST=postgresql-master
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PW=admin
    - POSTGRES_DB=catalog-service

  postgresql-master:
    image: bitnami/postgresql:12
    container_name: postgresql-master
    ports:
    - 5432:5432
    volumes:
    - .data/postgresql_master:/bitnami/postgresql
    environment:
    - POSTGRESQL_PASSWORD=admin # username=postgres
    - POSTGRESQL_DATABASE=catalog-service

  objectstore:
    image: minio/minio
    container_name: objectstore
    ports:
    - 9000:9000
    environment:
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    - MINIO_BROWSER=on
    entrypoint: sh
    command: -c 'mkdir -p /data/catalog && /usr/bin/minio server /data'

  objectstore-seed:
    image: alpine/openssl:latest
    container_name: objectstore-seed
    volumes:
    - ./seed/:/seed
    entrypoint: >
      /bin/sh -c '
      apk add curl;
      sh /seed/s3_putdir.sh objectstore:9000 catalog /seed/images;
      exit 0;'
    depends_on:
    - objectstore

  set-bucketpolicy:
    image: minio/mc:RELEASE.2021-03-12T03-36-59Z
    container_name: set-bucketpolicy
    entrypoint: >
      /bin/sh -c '
      mc config host rm local &&
      mc config host add local "http://objectstore:9000" minioadmin minioadmin &&
      mc policy set public local/catalog
      '
    depends_on:
    - objectstore-seed
