---
version: "3.8"
services: 

  postgresql-master:
    image: bitnami/postgresql:12
    container_name: postgresql-master
    ports:
    - 5432:5432
    volumes:
    - .data/postgresql_master:/bitnami/postgresql
    environment:
    - POSTGRESQL_USERNAME=admin
    - POSTGRESQL_PASSWORD=admin
    - POSTGRESQL_POSTGRES_PASSWORD=admin
    - POSTGRESQL_DATABASE=catalog-service
