---
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: catalog-service
    context: .

deploy:
  helm:
    releases:
    - name: catalog-service
      chartPath: ../../kubernetes/catalog-service
      valuesFiles:
      - ../../kubernetes/catalog-service/values.yaml
      artifactOverrides:
        image.repository: catalog-service
      version: 0.1.0
      # namespace: default
