apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust
  name: locust
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: locust
  type: ClusterIP
