---
apiVersion: v1
kind: Service
metadata:
  name: bullshit-service
  labels:
    {{- include "bullshit-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: bullshit-service
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
