---
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: payment-service
    context: .

deploy:
  helm:
    releases:
    - name: payment-service
      chartPath: ../../kubernetes/payment-service
      valuesFiles:
      - ../../kubernetes/payment-service/values.yaml
      artifactOverrides:
        image.repository: payment-service
      version: 0.1.0
      # namespace: default
