apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-service.fullname" . }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "catalog-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "catalog-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "catalog-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: seed-objectstore
          image: {{ .Values.image.repository }}
          command: ['bash', '-c', '/seed/s3_putdir.sh "{{ .Release.Name }}-objectstore.{{ .Release.Namespace }}" {{ .Values.objectstore.initialBucket }} /seed/images']
        - name: set-bucketpolicy
          image: minio/mc:RELEASE.2021-03-12T03-36-59Z
          command: ['bash', '-c', 'mc config host rm local && mc config host add local "http://{{ .Release.Name }}-objectstore.{{ .Release.Namespace }}" {{ .Values.objectstore.accessKey }} {{ .Values.objectstore.secretKey }} && mc policy set public local/{{ .Values.objectstore.initialBucket }}']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}
          # image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.server.port }}
            protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: {{ .Values.server.livenessPath }}
              port: http
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.server.springProfile }}
          - name: SERVER_HOST
            value: {{ .Values.server.host }}
          - name: SERVER_PORT
            value: "{{ .Values.server.port }}"
          - name: LOGGER_LEVEL
            value: {{ .Values.server.loggerLevel }}
          - name: POSTGRES_HOST
            value: "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}"
          - name: POSTGRES_PORT
            value: "{{ .Values.server.postgresql.port }}"
          - name: POSTGRES_USER
            value: {{ .Values.server.postgresql.user }}
          - name: POSTGRES_PW
            value: {{ .Values.server.postgresql.pw }}
          - name: POSTGRES_DB
            value: {{ .Values.server.postgresql.db }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
