---
apiVersion: skaffold/v2beta7
kind: Config

deploy:
  helm:
    releases:
    - name: loadgenerator
      chartPath: ../../kubernetes/loadgenerator
      valuesFiles:
      - ../../kubernetes/loadgenerator/values.yaml
      version: 0.1.0
      # namespace: default
