root: true
env:
  node: true
  jest: true
extends:
- google
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
- '@typescript-eslint'
rules:
  require-jsdoc: 0
  no-unused-vars: 0
  new-cap: 0
  '@typescript-eslint/explicit-member-accessibility':
  - error
  '@typescript-eslint/no-unused-vars':
  - warn
